### ISSUE TITLE
marquee is unlikely to be removed

### ISSUE THREAD

**Issue by karlcow** [styfle/breaking-changes-web#12]
The [marquee element](https://html.spec.whatwg.org/multipage/rendering.html#the-marquee-element-2) is still in the spec and unlikely to be ever un-shipped. One reason is specifically legacy websites. A lot of websites of India are still using it and for webcompat reasons, we can't just break these sites.

**Comment by styfle** [comment]
So marking as [obsolete](https://html.spec.whatwg.org/multipage/obsolete.html) is not the same as intent to remove?

**Comment by karlcow** [comment]
You can see two parts of it:

* As an author, do not use it, the intent is to remove it.
* As a browser implementer, it will not be possible to remove it for a very very long time. Because legacy websites don't go away that easily and in the case of marquee, a lot of university/gov websites are [using it](https://www.chromestatus.com/metrics/feature/popularity#HTMLMarqueeElement).

**Comment by urish** [comment]
If you still want to give another example, [`<blink>`](https://caniuse.com/?search=blink) has been removed and is no longer supported by any modern browser.

To make things a bit more interesting and add a fun bit of trivia, JavaScript there's a memorial for this element: every string in JavaScript has the `.blink()` method, which returns the given string wrapped in a `<blink>` element.

Also, a [nighttime story about blink](http://www.montulli.org/theoriginofthe%3Cblink%3Etag)
