### ISSUE TITLE
Intent to Remove: HTTP/2 and gQUIC server push

### ISSUE THREAD

**Issue by styfle** [styfle/breaking-changes-web#5]
https://groups.google.com/a/chromium.org/g/blink-dev/c/K3rYLvmQUBY/m/vOWBKZGoAQAJ

https://news.ycombinator.com/item?id=25064855

**Comment by chris-morgan** [comment]
This is not a breaking change. As the intent to remove notice says:

> **Interoperability and Compatibility Risk**  
> There is no compatibility risk.  Server push is meant as a performance optimization, a client is allowed to choose to reject any pushed streams.  In order to minimize wasted downlink capacity, Chromium would cancel pushed streams that a buggy server might open despite Chromium disabling server push by sending SETTINGS_ENABLE_PUSH = 0 in the initial SETTINGS frame.  Note however that in the experiment conducted two years ago no server was observed to send pushes when this setting was sent.

**Comment by styfle** [comment]
Good point! It might slow down but won't break.

Might be relevant if someone creates https://www.canistilluse.com to indicate removal of the feature.
