### ISSUE TITLE
Dating

### ISSUE THREAD

**Issue by ghost** [styfle/breaking-changes-web#9]
For whom the events were added by, could they also include the times, too?

**Comment by styfle** [comment]
Sounds like a good idea!

Note that each browser might remove at a different date so we might need multiple dates per feature.

Feel free to submit a PR 👍

**Comment by ghost** [comment]
> browser might remove at a different date

Could you explain?

**Comment by styfle** [comment]
Each browser can decide when it it will remove (or change) a feature.

I don't think `SameSite=Lax` cookie change was shipped to all browsers on the same date.

So there are different dates depending on the browser.

**Comment by ghost** [comment]
Maybe specify which browser the change was applied toward? 🤷🏻‍♂️

**Comment by styfle** [comment]
Sounds good to me 👍 

Do you want to submit a PR?
